### ISSUE TITLE
another question

### ISSUE THREAD

**Issue by dollylly** [TheGodOfObelisk/dailystudy#2]
Hey I'm sorry to disturb you  for the question about 'STUCCO' project.(because the question of your under it is closed).  I am doing the same project as you, but I just do the name entity recognition in the cyber security.  I'd like to know how you settle down the problem that the url 10.10.10.100:8000 can't access.  thanks!

**Comment by TheGodOfObelisk** [comment]
I don't know which version of 'STUCCO' project you are referring to. There are two versions: "demo" and "dev-setup".
If you are configuring "demo", you need to make some changes to the stucco.json file, just as the README suggested.
If you are configuring "dev-setup", you need to fix the provisioning after executing "vagrant up". I setup it using Ubuntu ( isn't in virtual machine).

**Comment by dollylly** [comment]
thank you for the reply!  I configured the "dev-setup" one but using the Ubuntu in a virtual machine, maybe that's the problem.  And sincerely, can I get your email address or any  contact for the further communication? (Please forgive my bearishness) Here's my account in QQ: 1070295820.  If you mind , it also doesn't matter. Anyway, thanks for your help again.
